services:
  postgres:
    image: postgres:16
    container_name: uhome-postgres
    restart: always
    environment:
      POSTGRES_USER: uhome
      POSTGRES_PASSWORD: uhome
      POSTGRES_DB: uhome
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
